spring:
  application:
    name: todo-backend
  profiles:
    default: dev
  cache:
    type: redis
  flyway:
    locations: classpath:db/migration
  mail:
    from: ${MAIL_FROM}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: ${MAIL_PROTOCOL}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

komapper:
  dialect: mysql

security:
  access-token-ttl: ${SECURITY_ACCESS_TOKEN_TTL:3600}
  refresh-token-ttl: ${SECURITY_REFRESH_TOKEN_TTL:86400}
  secret-key: ${SECURITY_SECRET_KEY}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
